version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: store_zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    container_name: store_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  cassandra:
    image: cassandra:latest
    container_name: store_cassandra
    environment:
      - "TZ=Europe/Amsterdam"
      - "CASSANDRA_USER=store"
      - "CASSANDRA_PASSWORD=store"
    ports:
      - "9042:9042"  # credentials (store:store)
